---
- name: Deploy MovieApp containers
  hosts: movieapp_servers
  become: yes
  vars:
    frontend_image: "{{ docker_registry }}/movieapp-frontend:{{ build_number }}"
    backend_image: "{{ docker_registry }}/movieapp-backend:{{ build_number }}"

  tasks:
    - name: Login to Docker Registry
      docker_login:
        username: "{{ lookup('env', 'DOCKER_CREDS_USR') }}"
        password: "{{ lookup('env', 'DOCKER_CREDS_PSW') }}"

    - name: Pull Docker images
      docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - "{{ frontend_image }}"
        - "{{ backend_image }}"

    - name: Run Frontend container
      docker_container:
        name: movieapp-frontend
        image: "{{ frontend_image }}"
        state: started
        restart_policy: always
        ports:
          - "80:3000"

    - name: Run Backend container
      docker_container:
        name: movieapp-backend
        image: "{{ backend_image }}"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
        env:
          DATABASE_URL: "your-database-url"
          API_KEY: "your-api-key"