---
- name: Deploy MovieApp
  hosts: movieapp_servers
  become: yes
  tasks:
    - name: Ensure Docker is installed (RedHat-based systems)
      package:
        name: docker
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Ensure Docker is installed (Debian-based systems)
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ensure Docker is installed (Ubuntu)
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    # Your existing deployment tasks
    - name: Pull and deploy frontend container
      docker_container:
        name: movieapp-frontend
        image: "{{ docker_registry }}/movieapp-frontend:{{ build_number }}"
        state: started
        restart_policy: always
        exposed_ports:
          - "80"
        published_ports:
          - "80:80"

    - name: Pull and deploy backend container
      docker_container:
        name: movieapp-backend
        image: "{{ docker_registry }}/movieapp-backend:{{ build_number }}"
        state: started
        restart_policy: always
        exposed_ports:
          - "5000"
        published_ports:
          - "5000:5000"
