---
- name: Deploy MovieApp
  hosts: movieapp_servers
  become: yes
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Ensure app directory exists
      file:
        path: /home/ec2-user/movieapp
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Copy docker-compose.yml
      copy:
        src: ../movieapp-backend/docker-compose.yml
        dest: /home/ec2-user/movieapp/docker-compose.yml
        owner: ec2-user
        group: ec2-user

    - name: Pull and restart containers
      community.docker.docker_compose:
        project_src: /home/ec2-user/movieapp
        pull: yes
        remove_orphans: yes
        restart: yes
      environment:
        MONGO_URI: "{{ mongo_uri }}"
        PORT: "{{ backend_port }}"
        REACT_APP_API_URL: "{{ api_url }}"