---
- name: Deploy MovieApp to EC2
  hosts: movieapp_servers
  become: yes
  tasks:
  
    - name: Install Docker (if not installed)
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log into Docker Hub
      command: "docker login -u pavithra0228 -p {{ lookup('env', 'DOCKER_PASSWORD') }}"

    - name: Pull the latest image
      command: "docker pull pavithra0228/movieapp-frontend:{{ lookup('env', 'BUILD_NUMBER') }}"

    - name: Stop any running container
      command: "docker stop movieapp-frontend || true"
      ignore_errors: yes

    - name: Remove old container
      command: "docker rm movieapp-frontend || true"
      ignore_errors: yes

    - name: Run Docker container
      command: >
        docker run -d --name movieapp-frontend -p 80:3000 
        pavithra0228/movieapp-frontend:{{ lookup('env', 'BUILD_NUMBER') }}
