---
- name: Install Docker on EC2 instance
  hosts: all
  become: yes
  tasks:
    # Update apt package index
    - name: Update apt cache
      apt:
        update_cache: yes

    # Install necessary dependencies
    - name: Install required dependencies for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    # Add Docker's official GPG key
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Gather system facts to get the Ubuntu release codename
    - name: Gather system facts
      ansible.builtin.setup:

    # Add Docker repository dynamically based on the Ubuntu release codename
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename | lower }} stable"
        state: present

    # Install Docker
    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    # Install Docker Compose
    - name: Download Docker Compose
      get_url:
        url:  "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x'

    # Start Docker service
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    # Test Docker installation
    - name: Check Docker version
      command: docker --version
      register: docker_version

    - name: Show Docker version
      debug:
        var: docker_version.stdout
